CREATE TABLE EMPLOYEES
(
ID NUMBER(8,1) NOT NULL PRIMARY KEY,
CREATE_DATE TIMESTAMP(6), 
CREATE_USER VARCHAR2(255 CHAR),
LAST_UPDATE_DATE TIMESTAMP(6),
LAST_UPDATE_USER VARCHAR2(255 CHAR),
FIRST_NAME VARCHAR2(255 CHAR) NOT NULL,
LAST_NAME VARCHAR2(255 CHAR) NOT NULL,
EMAIL VARCHAR2(255 CHAR)
)