CREATE TABLE FINDINGS
(
ID NUMBER(8,1) NOT NULL PRIMARY KEY, 
CREATE_DATE TIMESTAMP(6), 
CREATE_USER VARCHAR2(255 CHAR),
LAST_UPDATE_DATE TIMESTAMP(6),
LAST_UPDATE_USER VARCHAR2(255 CHAR),
MFR_NAME VARCHAR2(255 CHAR),
DESCRIPTION CLOB,
F_TYPE VARCHAR2(64 CHAR)NOT NULL,
APPROVED NUMBER DEFAULT 1 NOT NULL,
MANUFACTURER_ID NUMBER(8,2) 
)